### PR TITLE
- added super initial gif support

### PR DESCRIPTION
**Pull request by tht7**
# Checklist
- [x] I have read [CONTRIBUTING.md](./CONTRIBUTING.md)
- [x] I have described what this PR contains
- [ ] This PR addresses one or more open issues that were assigned to me:
      - *list issue(s) here*
- [x] If this PR alters the UI, I have attached pictures/videos

# Pull Request Information

## About this Pull Request
**Describe what this PR contains in as much detail as possible**

## Screenshots and Videos
**In case this PR changes something in the UI, please include screenshots or videos of this new feature**

https://github.com/mlemgroup/mlem/assets/6067331/cb4f2704-6990-4241-b52e-fe20ae90ea1c

https://github.com/mlemgroup/mlem/assets/6067331/71280d79-ee35-4d7e-84fd-5ad44282ddcd

## Additional Context
**Any additional context you'd like to add to help us review this PR**

### CODE REVIEW

**Comment by EricBAndrews** [comment]
Freezing this until 1.0 is out, but great work!

**Comment by WestonHanners** [comment]
Should we close this? Since @tht7 is redoing it anyways?

**Comment by EricBAndrews** [comment]
Yeah, this is about as stale as it gets

**Comment by tht7** [comment]
Definitely not relevant anymore, working on a brand new one

**Pull request closed without merging**
