### PR TITLE
Navigation System Tweaks

### PR DESCRIPTION
**Pull request by Sjmarf**
- Fixed account login sheet not opening.
- The quick switcher and login sheets now use the navigation system (all sheets need to use the navigation system for it to work properly).
- The `.sheet` modifier used for the navigation system is now attached *above* the `TabView`, rather than inside each tab as I had done previously.
- The quick switcher will dismiss itself when the app moves to the background, unless the login sheet is open on-top.
- Added all 5 tabs, with empty views in each. Tab icon discussion raised in Slack.
- Removed unused code.

### CODE REVIEW

**Comment by Sjmarf** [comment]
Drafting; I thought of a couple of ways I can improve this

**Comment by Sjmarf** [comment]
Switched to the tab icon design we currently use in 1.0

**Review by EricBAndrews — CHANGES_REQUESTED** [review]
Code looks good, but I can't run it--it compiles successfully, but on launch I get:

`Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: SwiftUI.AnyNavigationPath.Error.comparisonTypeMismatch`

**Comment by Sjmarf** [comment]
Fixed 👍

**Review by EricBAndrews — APPROVED** [review]
LGTM 👍

**Pull request merged**
