### PR TITLE
Fix "Official Community" link, Improve navigation routing pattern

### PR DESCRIPTION
**Pull request by boscojwho**
# Checklist
- [x] I have read [CONTRIBUTING.md](./CONTRIBUTING.md)
- [x] I have described what this PR contains
- [x] This PR addresses one or more open issues that were assigned to me:
      - Follow up to PR #644 
- [x] If this PR alters the UI, I have attached pictures/videos

# Pull Request Information

## About this Pull Request
- FIX: "Official Community" link in Settings now opens in app again (not in-app browser).
- Streamlines navigation routes logic and naming.

## Screenshots and Videos
- No UI changes.

## Additional Context
- Next step: Considering putting all `/Navigation` logic in an embedded SPM package.

### CODE REVIEW

**Review by EricBAndrews — CHANGES_REQUESTED** [review]
Official Community link still does not work if you connect using an account not registered on lemmy.world. That URL needs to adapt to the host of the user.

Other than that, looks good!

**Comment by boscojwho** [comment]
> Official Community link still does not work if you connect using an account not registered on lemmy.world. That URL needs to adapt to the host of the user.
> 
> Other than that, looks good!

Interesting: 
- This happens on `beta-1.0.1-RC-2` (ff5d8f75b76c9e72aea684eab3b74d3d8d2d8a59)
- Tested with my account on `lemmy.world` (opens in-app) and `test.mlem.jo.wtf` (opens in browser).
- I'm not familiar with the Link Resolver, is this something related to whether an instance is federated with `lemmy.ml`, where our community page is hosted?

**Review by EricBAndrews — APPROVED** [review]
🚀

**Comment by EricBAndrews** [comment]
Federation is the likely culprit. Until we have guest mode and can use that as a fallback, let's go with it as-is.

**Pull request merged**
