### PR TITLE
Mod/Admin Rank Awareness

### PR DESCRIPTION
**Pull request by EricBAndrews**
# Checklist
- [x] I have read CONTRIBUTING.md
- [x] I have described what this PR contains
- [x] If this PR alters the UI, I have attached pictures/videos
- [ ] This PR addresses one or more open issues that were assigned to me:
      - closes #issue
      - progress towards #issue

# Pull Request Information

This PR adds rank awareness to displaying highly destructive moderation and administration actions.

Lower-rank admins are no longer presented the following options on higher-rank admins or their content:
- Instance ban
- Purge
- Community moderation actions (remove/restore/ban)

Lower-rank moderators are no longer presented the following options on higher-rank moderators oor their content:
- Community moderation actions (remove/restore/ban)

### CODE REVIEW

**Review by Sjmarf — CHANGES_REQUESTED** [review]
Looks good. Moderator actions aren't shown when moderating a post from the feed - they're only shown in the expanded post.

**Comment by EricBAndrews** [comment]
I've basically completely rewritten this. Now `SiteInformationTracker` fetches full community information for all of the user's moderated communities, which is then used to check mod rank; this lets us check mod rank in aggregate feeds without fetching full community information. `canModerate` and `canAdministrate` are now functions on the `SiteInformationTracker`; `UserModel.canBeAdministrated` is still present for `Purgable` conformance, since the purge conditions are a little different for users and communities.

**Review by Sjmarf — CHANGES_REQUESTED** [review]
Nice, this is definitely cleaner. A couple of quirks:
- The "ban" option is shown for your own comments (it shouldn't be).
- When clicking on a post from the "subscribed" feed (not from a community feed), the moderation actions aren't shown in the ellipsis menu.

**Comment by EricBAndrews** [comment]
Nice catch! Should be fixed now.

**Review by Sjmarf — APPROVED** [review]
LGTM 🚀

**Pull request merged**
