### PR TITLE
NSFW toggle changes

### LINKED ISSUE #290: NSFW tag toggle in 'new post' sheet doesn't support dark mode
Not sure if this is intentional. I'd like to be assigned this task if it's something you think we should change.

image

image

image

image

### PR DESCRIPTION
**Pull request by Sjmarf**
Fixes the NSFW toggle in the New Post sheet not matching dark mode. Closes #290.

### CODE REVIEW

**Comment by Sjmarf** [comment]
Closes #290

**Comment by Sjmarf** [comment]
> changes look good
> 
> I still think this toggle isn't clear that it's a ... toggle 🙈 🤷
> 
> it doesn't look like a button or a toggle in it's default state, just greyed out text 🤔

I could try a different background color to make it stand out a bit more?

**Comment by Sjmarf** [comment]
Screenshot 2023-07-21 at 20 37 50
Screenshot 2023-07-21 at 20 37 44

**Review by WestonHanners — APPROVED** [review]

**Comment by WestonHanners** [comment]
We could do a normal-ass switch with this as the label.

**Comment by EricBAndrews** [comment]
I'm on board with the normal switch idea--tint it .red for visual consistency?

**Comment by Sjmarf** [comment]
> I'm on board with the normal switch idea--tint it .red for visual consistency?

Sure. 

Screenshot 2023-07-21 at 20 57 28

**Comment by EricBAndrews** [comment]
Looks good to me!

**Pull request merged**
