### PR TITLE
Boscojwho/experimental settings

### PR DESCRIPTION
**Pull request by boscojwho**
# Checklist
- [x] I have read [CONTRIBUTING.md](./CONTRIBUTING.md)
- [x] I have described what this PR contains
- [x] This PR addresses one or more open issues that were assigned to me:
      - #427 
- [x] If this PR alters the UI, I have attached pictures/videos

# Pull Request Information

## About this Pull Request
Adds an "Experimental" section to settings view that only appears in all builds (including TestFlight) except for App Store.

## Screenshots and Videos
Simulator Screenshot - iPhone 14 Pro - 2023-08-04 at 19 00 46
Simulator Screenshot - iPhone 14 Pro - 2023-08-04 at 19 00 49

### CODE REVIEW

**Comment by EricBAndrews** [comment]
By and large I really like this idea, but I agree with @mormaer that some granularity would be extremely valuable

**Comment by boscojwho** [comment]
> > Personally, I'd prefer us to avoid introducing this to the codebase, if the main purpose of it is to allow switching between two values without the need to re-build, given it is a single flag it only allows flipping between two values for testing and also lacks granularity if you wanted to control different settings independently.
> 
> To expand on my above comment, as re-reading it it may come across as dismissive (apologies, I was short on time!) 🙃
> 
> I don't object to the idea of having experimental features (aka 'Labs') in the project. I think that would be a nice addition, and I enjoy seeing that in other apps I use. Even one of my banking apps has them. My objection is just to the proposed approach here where there is a single global flag to switch things on/off.
> 
> I feel that a global approach only really solves the problem for a single developer looking to test a single change/feature on their branch, at which point I think it should be kept on the branch rather than introduced to the project as a whole. Once it's in the project and potential in use by multiple devs granularity becomes a must.
> 
> What I would support would be a more granular system where individual features/experiments could be toggled on and off.
> 
> In addition to that, rather than determine the environment in code at runtime we should consider making use of `xcconfig` files so that we can define our environments without relying on values that may change.

Absolutely haha, I meant for this to actually have actual feature flags or sliders (etc.) to adjust certain values, as in if you enable the "use experimental features" toggle, it would reveal all the available options.

I figured it'd be easier to kickstart discussions/preview some of that code with a PR since I'm working on my own forked version =)

- One use case I wanted this for was changing some spring animation values, which I just wanted to change throughout the day while I'm using the app and dial in what felt nice.
- Agree, we'll need `xcconfig` env values at some point.

Having to manually change the `bundle id` to `[bundle id].dev` and open Xcode to change values is getting a bit tedious, so anything to change that workflow would be nice =)

**Comment by boscojwho** [comment]
Would be great to hear more ideas on how everyone wants to see this implemented.

**Comment by EricBAndrews** [comment]
Closing this as stale--it's a good idea, though, we can definitely revisit if a use case arises

**Pull request closed without merging**
