### PR TITLE
Tab navigation custom behaviours

### PR DESCRIPTION
**Pull request by boscojwho**
# Pull Request Information

## About this Pull Request
Allows users to customize tab bar actions behaviour:
- System: Pop to root, then scroll to top (and pop back to sidebar, if available).
- Dismiss: Go back to previous page until root page, then scroll to top (and pop back to sidebar, if available).
- Dismiss after Scroll: Always scroll-to-top before going back to previous page (and pop back to sidebar, if available).

Appreciate any input on behaviour naming and explanation text.

### CODE REVIEW

**Comment by Sjmarf** [comment]
I think the wording here should be clarified somewhat. 

Would an inline list picker give us more space (the one with the checkmarks)? Maybe it could be titled "Tap tab bar icon to..." and have the following options:

- "Do nothing"
- "Scroll to top"
- "Return to previous page"
- "Return to first page"

**Comment by boscojwho** [comment]
> I think the wording here could be improved somewhat.
> 
> Would an inline list picker give us more space (the one with the checkmarks)? Maybe it could be titled "Tap tab bar icon to..." or "When I tap the tab bar icon..." and have the following options:
> 
> * "Do nothing"
> * "Scroll to top"
> * "Return to previous page"
> * "Return to first page"

Yea, that could work better, will tweak and update

**Comment by Sjmarf** [comment]
Looks good! I think it might look a little better in Title Case, without the trailing ellipses?

**Comment by EricBAndrews** [comment]
We might want to move all the tab bar stuff into its own section of Settings--with this PR we're going to have:
- Account switcher behavior in Profile
- Tab bar appearance in Appearance
- Tab tap behavior in General

Certainly not a blocker to this PR though

**Comment by Sjmarf** [comment]
That could work. 

What about the other categories? There are other cases where we will have a similar split-up grouping in future. An example would be when we add swipe action customisation, which in our current layout would go inside of a new "Gestures" page. That splits them up from the interaction bar customisation, which feels slightly off to me. And what if we then add ellipsis menu customisation too? Where would that go? It would be strange to put that in Appearance.

One solution go the proposed tab-bar settings route for the other categories too, and simply put all of the navigation links that are currently under Appearance under the root view. Then, gestures and ellipsis menu customisation could go in the same menu as appearance settings.

**Comment by boscojwho** [comment]
> Looks good! I think it might look a little better in Title Case, without the trailing ellipses?

Both work, I chose the ellipses without title case to indicate that there's more to the action than the literal name (i.e. nudge users to read the footer text lol)

**Comment by EricBAndrews** [comment]
Re: menu names--these behaviors are super complex to put in a tiny little switcher item. Ellipsis + footer works well enough for me as a pro tem solution, but longer term we might want to look into using animations to describe the behavior the way we do with the quick switcher

**Comment by boscojwho** [comment]
> Re: menu names--these behaviors are super complex to describe in a single list entry. Ellipsis + footer works well enough for me as a pro tem solution, but longer term we might want to look into using animations to describe the behavior the way we do with the quick switcher

Yea, eventually animations, figured I'd get this in without them for now because of time.

**Review by EricBAndrews — CHANGES_REQUESTED** [review]
Nice! Works pretty much perfectly. I found a couple minor defects while testing:
- Scroll to Top does not behave properly in Community view
- Do Nothing still scrolls to top in Feeds view

**Comment by EricBAndrews** [comment]
Closing this as stale

**Pull request closed without merging**
