### PR TITLE
Clip comment view in posts

### LINKED ISSUE #1041: Collapsing comments can overlap with post
**Describe the bug**
When collapsing comments, especially towards the top of the comment chain, large comments and especially those with embedded images can overlay the post. This is a very minor visual only glitch.

**Expected Behavior**
When comments collapse, they should not overlap with the post content.

**Actual Behavior**
Comments can overlap with the post. I took a video and the results can be seen in the post. It can be reproduced well on the post located at: https://lemmy.world/post/14696898.

https://github.com/mlemgroup/mlem/assets/1799888/7e74cd88-a016-4cc7-b39b-871697304eda

**To Reproduce**
Visit the lemmy post [here](https://lemmy.world/post/14696898) inside the mlem app and collapse the comments to have the image embedded in a comment overlap the post content when it is collapsed.

**Mlem Information:**
v1.2 (847)

### PR DESCRIPTION
**Pull request by made2k**
# Checklist
- [x] I have read CONTRIBUTING.md
- [x] I have described what this PR contains
- [x] If this PR alters the UI, I have attached pictures/videos
- [x] This PR addresses one or more open issues that were assigned to me:
      - closes #1041 

# Pull Request Information

## About this Pull Request

Fixes #1041 where the issue was that the comment collapse animations could show the comments overlapping the post. By adding the `.clipped()` view modifier on the comments view inside of the post the comments no longer clip into the featured post when collapsed.

## Screenshots and Videos

The linked issue (#1041) has a video of the issue, here is a similar video showing the fix.

https://github.com/mlemgroup/mlem/assets/1799888/98c7392c-ffc8-4346-966a-8927eae9fb54

### CODE REVIEW

**Review by EricBAndrews — APPROVED** [review]
LGTM 👍

**Comment by made2k** [comment]
Thank you for taking a look at the PR!

Looking at the build actions, I'm not sure if I know what is causing the error: `Resource not accessible by integration`. Otherwise, the xcodebuild build and test actions seem to pass, so maybe something with permissions when coming from a fork?

The only difference I can tell is this workflow is being kicked off from a fork rather than a branch in this source repo. Let me know if you have any ideas, or if there is anything I can do to help out with this. Thanks!

**Comment by Sjmarf** [comment]
Yeah, the tests are broken for forks right now unfortunately. Eric will have to override it

**Comment by EricBAndrews** [comment]
Build and test pass locally--overriding CI requirements and merging.

**Pull request merged**
