### PR TITLE
Made links easier to tap

### LINKED ISSUE #746: Make the links more hittable
Links in post bodies can be very hard to tap. They should be parsed and aggregated (probably at the bottom of the post) as nice big tappable elements. 

Would make #116 trivially easy.

### PR DESCRIPTION
**Pull request by EricBAndrews**
# Checklist
- [x] I have read [CONTRIBUTING.md](./CONTRIBUTING.md)
- [x] I have described what this PR contains
- [x] This PR addresses one or more open issues that were assigned to me:
      - closes #746 
- [x] If this PR alters the UI, I have attached pictures/videos

# Pull Request Information

This PR makes links embedded in post and comment content easier to hit by parsing them out of the body and aggregating them as nice easy-to-tap elements at the bottom. Links are given a title and caption according to the following schema:
- Raw links: destination host, full url
- Markdown links: markdown label, full url
- User links: /u/username, username@instance
- Community links: /c/community, community@instance

This PR also modifies the link handling code a little bit to properly allow navigation to communities using webfingers links (`!community@instance`)--Markdown parses those into `mailto:` links, so any `mailto:` link is parsed back into its webfingers format and resolved.

Screenshot 2023-12-10 at 5 45 55 PM

Screenshot 2023-12-10 at 5 46 05 PM

### CODE REVIEW

**Comment by Sjmarf** [comment]
Nice! 

I noticed an issue where sometimes the links will fail to appear for some reason. See video

https://github.com/mlemgroup/mlem/assets/78750526/a9cb4cca-3d24-40fa-9e4d-0f637538b2a5

**Comment by EricBAndrews** [comment]
Whoops, tiny mistake in the PostModel initializer. Should work now.

**Comment by Sjmarf** [comment]
Thoughts on adding `.linelimit(1)`  to the URL, so that it can't go onto multiple lines? Some URLs can be rather long, and the path of the URL is unlikely to be of interest to the user.

image

**Comment by boscojwho** [comment]
> Thoughts on adding `.linelimit(1)` to the URL, so that it can't go onto multiple lines? Some URLs can be rather long, and the full path of the URL is unlikely to be of interest to the user.
> 
> 
> The `/u/testmlem` and `/c/erictesting` links don't work for me in the test post - I get a `couldnt_find_object` notification. Is this an issue with this PR, or with the way we're handling lemmy links in general?
> 
> Also, on [this post](https://lemmy.world/post/9513168), it looks like an image was parsed as a link.
> 
> 

Yea, I agree with the line limit = 1 (or maybe up to 2).
Also seeing images being parsed into links, is this expected behaviour?

I'm testing with the list of lemmy apps megathread on c/lemmyapps (@lemmy.world).

**Comment by boscojwho** [comment]
Am getting a bunch of SwiftUI errors when opening this post [[Megathread] List of lemmy apps](https://lemmy.world/post/465785)
```
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID 5299731769841810004 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID 356312324165025707 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID 3852116958197994662 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID 190878897006581934 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID 5230544909353130416 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID -6930063565285225971 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID 4277696069875835156 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID -6095699629114587309 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID 571864367821928126 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID -2399923774384290428 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID -7243895541097590018 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID -7166985527651810472 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID 2555061807947476455 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID -7089268712642330647 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID 6956683248215157253 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID -3577856960335734765 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID -1781974060465096276 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID 4825427698802235078 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID 1312469715416903844 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID 7833049547064626999 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID -1284913285309379458 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID 8569667623883647841 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID -214600270161307259 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID -3586670969771899209 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID 56958448397598487 occurs multiple times within the collection, this will give undefined results!
ForEach<Array<LinkType>, Int, EasyTapLinkView>: the ID -2258161235183825776 occurs multiple times within the collection, this will give undefined results!
```

**Comment by Sjmarf** [comment]
The @username regex picks up usernames inside links, which causes undesired results:

image

image

https://kbin.social/m/technology@lemmy.world/t/700741/-/comment/4107680

**Comment by Sjmarf** [comment]
At some point it would be nice to have a 'copy link' context action on each link, but that doesn't necessarily have to be in this PR

**Comment by Sjmarf** [comment]
Here's another case where the parsing breaks

image

https://feddit.de/comment/5643260

**Comment by Sjmarf** [comment]
Found a duplicate link here:

image

**Review by Sjmarf — APPROVED** [review]
Look good!

**Pull request merged**
