### PR TITLE
Fix quicklook dismiss on rotate

### PR DESCRIPTION
**Pull request by boscojwho**
# Checklist
- [x] I have read [CONTRIBUTING.md](./CONTRIBUTING.md)
- [x] I have described what this PR contains
- [x] This PR addresses one or more open issues that were assigned to me:
      - #747 (reported via Lemmy community)
- [x] If this PR alters the UI, I have attached pictures/videos

# Pull Request Information

## About this Pull Request
1. Fixes issue where rotating device while QuickLookUI is presented causes that UI to be dismissed.
2. Adds a progress view overlay on top of CachedImage while QuickLookUI is preparing to open, since sometimes QuickLookUI doesn't immediately open on tap gesture.

## Screenshots and Videos

https://github.com/mlemgroup/mlem/assets/2549615/31b792ff-7480-4df8-82c3-f61818a5e0e0

## Additional Context
Rotation bug **might** not be reproducible in iOS simulator.

### CODE REVIEW

**Review by EricBAndrews — CHANGES_REQUESTED** [review]
This PR appears to break the "mark read on view image" functionality.

Repro:
- Tap an image in feed on an unread post
- Close the QuickLook preview

Expected behavior: post is marked read
Actual behavior: post is not marked read

Some very preliminary investigation indicates that the `dismissCallback` is getting called 2-4 times per dismissal, though why that causes the post to not be marked read at all is a bit of a mystery

**Comment by boscojwho** [comment]
> This PR appears to break the "mark read on view image" functionality.
> 
> Repro:
> 
> * Tap an image in feed on an unread post
> * Close the QuickLook preview
> 
> Expected behavior: post is marked read Actual behavior: post is not marked read
> 
> Some very preliminary investigation indicates that the `dismissCallback` is getting called 2-4 times per dismissal, though why that causes the post to not be marked read at all is a bit of a mystery

Ah, I thought that was just a simulator issue.

Yeah, odd, because callback gets called. Will investigate.

**Comment by boscojwho** [comment]
Self note:
On fresh launch, mark as read works on the first opened photo post. After that, it fails.

**Comment by boscojwho** [comment]
Resolved mark post as read issue:
- Tested in iOS simulator on lemmy.world instance in `compact`, `headline`, and `large` posts setup.

**Review by EricBAndrews — APPROVED** [review]
Nice 👍

**Pull request merged**
