### PR TITLE
Expand images in feed (large post size)

### PR DESCRIPTION
**Pull request by fer0n**
# Checklist
- [x] I have read [CONTRIBUTING.md](./CONTRIBUTING.md)
- [x] I have described what this PR contains
- [x] This PR addresses one or more open issues that were assigned to me:
      - #480
- [x] If this PR alters the UI, I have attached pictures/videos

# Pull Request Information
Removes limiting the height of images in the feed (large post size).

## Screenshots and Videos

| Currently | New |
|---|---|
| Simulator Screenshot - iPhone 14 Pro - 2023-08-14 at 08 08 50 | Simulator Screenshot - iPhone 14 Pro - 2023-08-14 at 08 10 36 |

There are two variants of how to expand the image:

| Masked with padding | full width |
|---|---|
| Simulator Screenshot - iPhone 14 Pro - 2023-08-14 at 08 10 02 | Simulator Screenshot - iPhone 14 Pro - 2023-08-14 at 08 10 49 |

The "full width" variant is the latest commit, the "masked with padding" variant is the commit before that.

### Old approach intentional?
I am not sure if the previous behaviour of cutting of the height was intentional, since this approach has the slight downside of potentially having to scroll over a perhaps quite long image post that the user is not interested in. Since this was relatively easy to implement I thought it wouldn't hurt to open a PR to discuss this. 

I'd argue that "the long image is annoying to scroll over" is far less common and having it the other way around, where a comic, meme, etc is being cut off and forces the user to tap, zoom/scroll, and dismiss to view the image happens way more often and is the bigger issue. Additionally, you might see a spoiler of a comic/the image, since the "view port" for the image is centred (aligning to the top while cutting off the height has different downsides ofc).

If the height should be limited for image posts, I think hiding the post content (text) would be the better choice. Better to see the full image and tap to see the discussion about it than see half of both. 

One alternative would also be to only expand the image when there's no text added to it and otherwise keep it the way it currently is. Or make it an option in settings to show images with their full height.

### Between the two variants
I'd go with the full width variant, because the image posts can be better differentiated from link previews and the additional width helps with seeing/reading smaller things in the image. The masked variant looks more uniform and has slightly less height, but I think that's negligible.

### CODE REVIEW

**Comment by fer0n** [comment]
Shrinking is a good solution as well, although I personally prefer just having it be a "native part of the feed". 

If you're thinking about making in an option, why not go all the way and make it unlimited? Moving from 400 to 800 doesn't seem to be a huge leap with the current image heights that I've come across and depending on the post you'd still have to scroll and zoom around in a second view.

Since you've already implemented it in your other PR, would you like me to add such an option on top of your commit? And close this one?

**Comment by EricBAndrews** [comment]
OK--let's try it with two options, shrunk and unlimited (that should be a settings toggle called "Limit Image Height In Feed", default on).

Let's  roll it into my in-flight--you can open a PR against `eric/feed-items` and we'll get them both merged at once, since they're both addressing the same issue

**Comment by fer0n** [comment]
Okay great :) 
I'll have a look tomorrow (in roughly 8h), so if you want to merge your PR in the meantime that's fine by me. I'll add it on top of yours then.

**Comment by EricBAndrews** [comment]
#501 is in fyi

**Comment by fer0n** [comment]
I'm having an issue that I didn't get past yet, maybe you know what's going on here or how to fix it: the size of the image itself won't change dynamically. Which means:
- Changing the setting is either not working (when turning the expansion on) or leads to the extended image being cut off half way down, with some overflow ([image]([Simulator Screenshot - iPhone 14 Pro - 2023-08-15 at 10 20 37](https://github.com/mlemgroup/mlem/assets/20093825/8b816d9a-4939-4ff6-bd12-7704d6044e4b))
- The post detail can't show the image collapsed if it should be expanded in the feed

I've spent quite some time trying to fix this, I'm assuming it's a layout issue, but maybe it's related to Nuke as well. Restarting of course solves it and it only affects images that have already been displayed. Any idea?

**Comment by fer0n** [comment]
Apart from that issue, I also made the shrunken version have rounded corners and slightly decreased the padding for images to make them look a bit different from links (maybe that helps subconsciously, I've seen people bring this up).
| round image | smaller image padding |
|---|---|
| Simulator Screenshot - iPhone 14 Pro - 2023-08-15 at 10 47 20  | Simulator Screenshot - iPhone 14 Pro - 2023-08-15 at 10 47 55  |

**Comment by EricBAndrews** [comment]
Re: image sizing: I ran into this same problem when I migrated the avatars to `CachedImage`--you'll notice that changing the "show user instance" results in the same bad behavior. `CachedImage` is slowly accumulating bloat and at this point is venturing into spaghetti territory--I *think* resizing is happening both on the main thread within the `LazyImage` closure *and* in the background using proper Nuke processors but with absolutely no logic to handle resizing. Unfortunately we can't really do much to it right now because of the in-flight media viewer (estimated to land within the next 2 weeks, maybe)--once we can pull QuickLook out of there and we have an idea of how the new viewer hooks up to the image we can properly refactor/rewrite. Since that resizing problem is an app-wide issue, this PR can go in without resolving it because it should theoretically be properly fixed when the issue itself is.

Re: visual tweaks--really love the rounded corners on shrunken images! Per the conversation over in the community, we already differentiate links in large posts with the website complex, so for the sake of margin consistency let's keep the padding the same.

**Comment by fer0n** [comment]
Yeah you're right about the padding, that did more harm than good. I removed it and cleaned everything up. I also added a max height for the expanded images (3000) which should be plenty but it's probably good to not have it be infinity. Should be good to go now if you think all that makes sense and don't have anything else to add :)

**Review by EricBAndrews — APPROVED** [review]

**Pull request merged**
